let dialog = [
//Title: "The Crystal Lies"
//Sequel to “The Quest for the Crystal of Clarity”",
//Setting: A sleek, high-tech facility. Monitors flicker. The Crystal now floats in a containment field. The team is being interviewed by mysterious figures in suits and dark glasses ... “The Agency.”,
"Setting: A sleek, high-tech facility. Monitors flicker. The Crystal now floats in a containment field. The team is being interviewed by mysterious figures in suits and dark glasses ... 'The Agency.'",
//"Scene 1 – Interrogation Room",
"Agent Vox (stoic, offstage voice): For the record, please state your names and the nature of your involvement with the artifact known as 'The Crystal.'",
"Captain Obvious: I'm Captain Obvious. We found the Crystal in a jungle temple. It was glowing, so we took it. That’s usually a sign something’s important.",
"Sarcastic Sally: Yeah, we just thought, hey, what’s the worst that could happen bringing a sentient light rock into civilization?",
"Optimistic Otto: We believed the Crystal could help humanity! We just wanted to do good!",
"Megalomaniac Marvin (restrained, in a containment chair): It spoke to me. Whispered secrets. It chose me. The others just… slowed destiny.",
//"Scene 2 – Observation Room",
"Narrator: (The agents watch the team from behind glass.)",
"Agent Vox: The Crystal's energy readings have spiked. It's no ordinary artifact. It’s... transmitting.",
"Agent Noir: To where?",
"Agent Vox: Not where. When.",
//"Scene 3 – Crystal Chamber, Night",
"Narrator: (The team is alone. The Crystal pulses again.)",
"Captain Obvious: That’s new. It's glowing faster than before. So... something must be happening.",
"Sarcastic Sally: Wow. It’s almost like bringing home a mysterious, ancient object full of cosmic power has consequences.",
"Optimistic Otto: Maybe it’s excited! Like it knows it’s about to help the world even more!",
"Megalomaniac Marvin (smirking): Or maybe it’s finally waking up.",
"Narrator: (The lights flicker. Sirens blare. The facility locks down.)",
"Voice Over Intercom: SECURITY BREACH. TEMPORAL RIFT DETECTED.",
//"Scene 4 – The Twist",
"Narrator: (From a swirling vortex, futuristic versions of the four characters step out ... more powerful, battle-worn, clearly changed.)",
"Future Captain Obvious (armored, serious): Stand down. We’re here to stop the Crystal from completing its loop.",
"Future Sarcastic Sally (eye patch, laser sword): Oh look, it's our clueless past selves. Adorable.",
"Future Optimistic Otto (grim, voice shaky): We tried to stay hopeful... but the Crystal doesn’t bring clarity. It brings control.",
"Future Megalomaniac Marvin (now a godlike villain, hovering behind them): And in every timeline... I win.",
"Narrator: (The Crystal levitates between them. It flashes ... splitting into two forms: a white, glowing shard... and a dark, pulsing one.)",
"Captain Obvious: So... the Crystal has a light and dark half.",
"Sarcastic Sally: Wow. Could this be any more symbolic?",
"Optimistic Otto: Maybe this means we have a choice! Maybe we can still fix it!",
"Megalomaniac Marvin: No. It means... we finish what we started."
];
