const dialog1 = [
    //"Act I — The Spark of Silence",
    //"",
    "Narrator: It was the very beginning of it all.",
    "Elias: The sky hasn’t spoken in days. I think it's waiting.",
    "Mira: Waiting? For what? For us?",
    "Elias: Or maybe for something deeper. Something old.",
    "Mira: Don’t be cryptic, Elias. Not today.",
    "Elias: Then listen closely, Mira. The earth is humming again.",
    "Mira: Humming? You mean like before the stillness?",
    "Elias: Yes. And the hum—it’s growing louder.",
    "Narrator: Beneath the soil, something stirs. Not with violence, but with memory.",
    "Mira: I feel it too. In my bones. Like a name I’ve forgotten.",
    "Elias: Then perhaps it’s time we remember.",
    //"",
    //"(End of Act I)",
    //"",
    //"Act II — The Name Beneath",
    //"",
    "Narrator: In the hush between heartbeats, truth sometimes slips through.",
    "Mira: Remember? Elias, we were children when the silence fell.",
    "Elias: Even children carry fragments. Dreams that weren’t dreams.",
    "Mira: You think the hum is calling those dreams back?",
    "Elias: Not calling. Summoning.",
    "Mira: That sounds like danger. Or destiny.",
    "Elias: Often they wear the same face.",
    "Narrator: A wind stirs the ashes of the old temple ruins nearby.",
    "Mira: The temple—do you think it remembers us?",
    "Elias: It remembers everything. We only need to ask the right question.",
    "Mira: Then ask.",
    "Elias: No. We ask—together.",
    //"",
    //"(End of Act II)",
    //"",
    //"Act III — The Question and the Ash",
    //"",
    "Narrator: The temple looms, neither ruin nor refuge, but something between.",
    "Mira: My voice feels small here. Like it’ll be swallowed whole.",
    "Elias: That’s how you know you’re standing somewhere sacred.",
    "Mira: Or haunted.",
    "Elias: Maybe both.",
    "Narrator: They step through the cracked arch, where lichen paints old prayers.",
    "Mira: The altar’s still here. And—Elias, look. The sigils are glowing.",
    "Elias: They only answer to shared breath, shared intent.",
    "Mira: Then say it with me.",
    "Elias & Mira: What was taken—return. What was lost—remember.",
    "Narrator: The hum becomes a voice. Not loud. Not clear. But unmistakably alive.",
    "Voice in Stone: You have asked. Will you endure the answer?",
    "Mira: That... wasn’t just in my head, was it?",
    "Elias: No. It never was.",
    //"",
    //"(End of Act III)",
    //"",
    //"Act IV — The Echo Unburied",
    //"",
    "Narrator: The air tightens, thick with the weight of a waiting truth.",
    "Voice in Stone: One of you carries the forgotten name. Speak it.",
    "Mira: I—I don’t know any name.",
    "Elias: Wait. Let it come. Don’t chase it.",
    "Narrator: A flicker of golden dust swirls around Mira’s hands.",
    "Mira: It’s burning. But it doesn’t hurt.",
    "Elias: That’s memory. Old as the roots.",
    "Mira: I see... a tree. Split by lightning. And beneath it, a cradle made of bone.",
    "Voice in Stone: Speak the name.",
    "Mira: Auren.",
    "Narrator: The temple trembles. The sigils pulse like heartbeats.",
    "Elias: That was it. That was the name.",
    "Voice in Stone: The seal is broken. The first gate opens.",
    "Mira: Gate? What gate?",
    "Narrator: And beneath the temple, something vast begins to breathe.",
    //"",
    //"(End of Act IV)",
    //"",
    //"",
    //"Act V — Beneath the Breathing Earth",
    //"",
    "Narrator: The ground shivers like a waking animal, slow and certain.",
    "Mira: Elias... something’s moving down there.",
    "Elias: Not something. Someone.",
    "Narrator: From the center of the altar, a spiral of stone recedes, revealing a stair carved into darkness.",
    "Voice in Stone: The gate is not a door. It is a descent.",
    "Mira: Are we meant to follow?",
    "Elias: We’ve already begun. Turning back would be forgetting again.",
    "Narrator: A warm wind rises from below, carrying the scent of moss, iron, and memory.",
    "Mira: I remember Auren now. Not just the name. The lullaby.",
    "Elias: Sing it. It might keep us whole on the way down.",
    "Mira: “Sleep where the root runs deep, sleep in the breath of stone...”",
    "Narrator: With each note, the darkness parts. Not with light, but with understanding.",
    "Elias: Hold my hand. We descend together.",
    "Narrator: And so they step below, not as seekers, but as something older reborn.",
    //"",
    //"(End of Act V)",
    //"",
    //"Act VI — The Rootward Path",
    //"",
    "Narrator: The stairs spiral like a question never asked aloud.",
    "Mira: It's warmer here than it should be.",
    "Elias: That’s the breath of the Deep Root. It remembers what the surface forgets.",
    "Narrator: Their footsteps echo, not ahead or behind—but beside.",
    "Mira: Do you hear that? It’s... like footsteps not our own.",
    "Elias: Don’t look for them. They walk with us when we listen, not when we search.",
    "Voice Below: Returners... you carry song and name. Do you carry cost as well?",
    "Mira: What cost? We’ve done only what was asked.",
    "Voice Below: All memory has weight. And yours tips the scale.",
    "Narrator: The stone corridor opens into a chamber shaped like a heart mid-beat.",
    "Elias: This is where they made the pact. Where the first silence began.",
    "Mira: Then this is where we end it.",
    "Voice Below: Or where you join it.",
    "Narrator: The walls pulse with roots lit from within—threads of gold, blood, and time.",
    "Elias: Speak it again, Mira. The lullaby.",
    "Mira: “Sleep where the root runs deep…”",
    "Narrator: The chamber listens. And something ancient leans closer to waking.",
    //"",
    //"(End of Act VI)",
    //"",
    //"Act VII — The Pact Rewritten",
    //"",
    "Narrator: The chamber holds its breath, as if deciding whether to remember or to consume.",
    "Voice Below: Memory is not yours to wield—it is yours to carry.",
    "Mira: Then let us carry it. Not buried. Not hidden.",
    "Elias: We offer no silence. Only truth.",
    "Narrator: A root splits from the ceiling, curling downward like a question mark made flesh.",
    "Mira: What do we do? Touch it? Speak to it?",
    "Elias: Neither. Listen.",
    "Narrator: The root hums, low and deep—a resonance older than language.",
    "Root Voice: You seek to wake what was sealed. Do you accept its hunger?",
    "Mira: If it feeds on truth, then yes.",
    "Elias: If it ends the forgetting, then yes.",
    "Narrator: The root brushes their foreheads, and a flicker of light passes between them.",
    "Mira: I see it. The day the silence began. The choice. The betrayal.",
    "Elias: They weren’t protecting us. They were protecting themselves.",
    "Voice Below: Now you choose. Let the silence stand... or let the root remember.",
    "Mira: We choose memory.",
    "Elias: We choose what was buried. Let it rise.",
    "Narrator: The chamber blooms. Light bursts through the root-veined walls, and far above, the temple sighs with release.",
    //"",
    //"(End of Act VII)",
    //"",
    //"Act VIII — The Rising Remembered",
    //"",
    "Narrator: Light climbs the spiral behind them, not to burn, but to reveal.",
    "Mira: The walls... they're stories. Etched in bark and bone.",
    "Elias: Not stories. Confessions.",
    "Narrator: Figures shimmer along the chamber's edge—echoes of those who sealed the silence.",
    "Echo of the First Sealer: We chose stillness over sorrow. It was a mercy.",
    "Mira: You buried the grief of a thousand voices.",
    "Echo of the First Sealer: Would you have borne them all?",
    "Elias: Yes. Because they were ours.",
    "Narrator: The root pulses once more. The echoes begin to dissolve, their weight transferred.",
    "Voice Below: Then carry them. Every name. Every wound.",
    "Mira: I feel them... not as pain, but as purpose.",
    "Elias: This is what remembering feels like. Heavy, but holy.",
    "Narrator: Aboveground, the temple cracks—not in ruin, but in awakening.",
    "Mira: What happens now?",
    "Elias: We return. Not as seekers. Not even as returners.",
    "Mira: Then what?",
    "Elias: As rememberers.",
    "Narrator: And as they rise, the silence does not follow. It stays behind, finally alone.",
    //"",
    //"(End of Act VIII)",
    //"",
    ];
    